<h2>Liste des catégories</h2>

<div>
<?php foreach ($categorys as $category): ?>
        <li><a href="categorie.php?id=<?= $category['ID'] ?>"><?= $category['name'] ?>(<?= $category['nbArt'] ?>)</a></li>

<?php endforeach ?>
</div>

<div>
    <?php foreach ($articles as $article): ?>
        <h2><a href="articles.php?title=<?= $article['title'] ?>"><?= $article['title'] ?></a></h2>
        <p>Article rédigé par <?= $article['firstname'] ?> <?= $article['lastname'] ?></p>
        <p> Créé le : <?= $article['creation_date'] ?></p>
        <p><?= $article['content'] ?></p>
    <?php endforeach ?>
</div>
