<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <script src="https://kit.fontawesome.com/3903820350.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav>
            <li><a href="index.php">Accueil</a></li>
            <li><a href="admin.php">Administration</a></li>
            <li><a href="login.php">Connexion</a></li>
            <li><a href="register.php">Inscription</a></li>
        </nav>
    </header>
    
    <main>
        <?php require $template . '.phtml' ?>
    </main>
</body>
</html>