<h1>CONNEXION</h1>

<form action ="login.php" method="post">

    <fieldset>

        <label for="email">Login</label>
        <input type="text" id="email" name="email"></input>
            
        <label for="password">Password</label>
        <input type="text" id="password" name="password"></input><br>
        
        <br><button type="submit" value="Submit">CONNEXION</button>

    </fieldset>

</form>