<h1>Rédiger un nouvel article</h1>

<form action="new_article.php" method="post">
    <fieldset>
        <label for="title">Titre:</label><br>
          <input type="text" id="title" name="title"><br>
          
        <label for="content">Contenu:</label><br>
          <textarea id="content" name="content" rows="8" cols="60"></textarea>
          <br>
        <label for="author">Auteur:</label>
            <select name="author_id" id="author">
                
                <?php foreach ($authors as $author): ?>
                    <option value="<?= $author['id'] ?>"><?= $author['firstName'] ?> <?= $author['lastName'] ?></option>>
                <?php endforeach ?>
                    
            </select>
        <br>
        <label for="category">Catégorie:</label>
            <select name="category_id" id="category">
                
                <?php foreach ($categories as $categorie): ?>
                      <option value="<?= $categorie['id'] ?>"> <?= $categorie['name'] ?></option>
                <?php endforeach ?>
                
            </select>
        <br>
        <button type="submit" value="Submit">Enregistrer</button> 
    </fieldset>
</form>