<h1>Inscription</h1>

<form action ="register.php" method="post">
    <fieldset>
        <label for="email">Email :</label><br>
          <input type="email" id="email" name="email"></input><br>
        
        <label for="password">Password :</label><br>
          <input type="password" id="password" name="password"></input><br>
          
        <label for="lastName">Prénom :</label><br>
          <input type="text" id="firstName" name="firstName"></input><br>
          
        <label for="lastName">Nom : </label><br>
          <input type="text" id="lastName" name="lastName"><br>

        <br><button type="submit" value="Submit">INSCRIPTION</button>
    </fieldset>
</form>